global:
  scrape_interval: "10s"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
          - 10.11.10.1:9100
          - 10.11.10.2:9100
          - 10.11.10.3:9100
          - 10.11.10.4:9100
          - 10.11.10.5:9100
