global:
  scrape_interval: "10s"
  evaluation_interval: "10s"
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  
  - job_name: node
    static_configs:
      - targets:
          - 10.11.10.1:9100
          - 10.11.10.2:9100
          - 10.11.10.3:9100
          - 10.11.10.4:9100
          - 10.11.10.5:9100
