version: '3.9'

services:
    blackbox: 
        image: prom/blackbox-exporter
        container_name: blackbox
        hostname: blackbox
        ports:
            - 9115:9115
        restart: unless-stopped
        command:
            - "--config.file=/etc/prometheus/blackbox/blackbox.yml"
        volumes:
            - ./blackbox:/etc/prometheus/blackbox
        environment:
            TZ: "Europe/Moscow"
        networks:
            - default
